"use client"
import { Provider } from 'react-redux'
import NavBar from '../../Components/NavBar'
import './globals.css'
import Store from '@/redux/Store'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Provider store={Store}>
    <html lang="en">
    <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
  integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
  crossorigin="anonymous"
/>
<link rel="stylesheet" href="../public/fontawsome-free-6.1.1-web/css/all.css"/>
{/* <link rel='stylesheet' href='../'/> */}
    {/* <metadata/> */}
      <body>
      <NavBar/>
      <main>
      {children}
      </main>
      </body>
    </html>
    </Provider>
  )
}
